# Generated by Django 4.1.6 on 2023-10-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumaguaAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebederos',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='bebederos',
            name='latitud',
            field=models.FloatField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bebederos',
            name='longitud',
            field=models.FloatField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
