# Generated by Django 4.0.10 on 2023-10-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bebederos',
            fields=[
                ('id_bebedero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('institucion', models.CharField(blank=True, max_length=100)),
                ('palabras_clave', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
